### PR TITLE
Companies that Whiteboard : adds Toptal

### PR DESCRIPTION
**Pull request by nicolasblanco**

### CODE REVIEW

**Comment by cheesesashimi** [comment]
First of all, thanks for your submission! It looks like Toptal is an aggregator / talent search / screening company whose goal is to place you with another company.

I think `_data/screening_companies.yml` might be a better place for this one.

**Comment by nicolasblanco** [comment]
@cheesesashimi : Eventually you work for Toptal. They use Codility.com as the screening company.

**Comment by cheesesashimi** [comment]
Understood. Your commit makes sense now.

**Review by cheesesashimi — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
